// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadAllBridges() {
  return window['go']['main']['App']['DownloadAllBridges']();
}

export function GenerateTorrc(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GenerateTorrc'](arg1, arg2, arg3, arg4);
}

export function GetBridgeFiles() {
  return window['go']['main']['App']['GetBridgeFiles']();
}

export function GetBridgeInfo() {
  return window['go']['main']['App']['GetBridgeInfo']();
}

export function GetBridgeLines(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetBridgeLines'](arg1, arg2, arg3);
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetSafeFilename(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetSafeFilename'](arg1, arg2, arg3);
}

export function GetTorExePath() {
  return window['go']['main']['App']['GetTorExePath']();
}

export function GetTrafficStats() {
  return window['go']['main']['App']['GetTrafficStats']();
}

export function GetUptime() {
  return window['go']['main']['App']['GetUptime']();
}

export function IsPortFree(arg1) {
  return window['go']['main']['App']['IsPortFree'](arg1);
}

export function IsTorConnected() {
  return window['go']['main']['App']['IsTorConnected']();
}

export function IsTorInstalled() {
  return window['go']['main']['App']['IsTorInstalled']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function ResetTrafficStats() {
  return window['go']['main']['App']['ResetTrafficStats']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetSystemProxy() {
  return window['go']['main']['App']['SetSystemProxy']();
}

export function StartHTTPProxy() {
  return window['go']['main']['App']['StartHTTPProxy']();
}

export function StartTor(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartTor'](arg1, arg2, arg3, arg4);
}

export function StopHTTPProxy() {
  return window['go']['main']['App']['StopHTTPProxy']();
}

export function StopTor() {
  return window['go']['main']['App']['StopTor']();
}

export function TestConnection() {
  return window['go']['main']['App']['TestConnection']();
}

export function TestSpeed() {
  return window['go']['main']['App']['TestSpeed']();
}

export function UnsetSystemProxy() {
  return window['go']['main']['App']['UnsetSystemProxy']();
}
