// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DownloadAllBridges():Promise<void>;

export function GenerateTorrc(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetBridgeFiles():Promise<Array<Record<string, string>>>;

export function GetBridgeInfo():Promise<main.BridgeOverview>;

export function GetBridgeLines(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;

export function GetDataDir():Promise<string>;

export function GetSafeFilename(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetTorExePath():Promise<string>;

export function GetTrafficStats():Promise<Record<string, string>>;

export function GetUptime():Promise<string>;

export function IsPortFree(arg1:number):Promise<boolean>;

export function IsTorConnected():Promise<boolean>;

export function IsTorInstalled():Promise<boolean>;

export function LoadConfig():Promise<main.Config>;

export function ResetTrafficStats():Promise<void>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SetSystemProxy():Promise<void>;

export function StartHTTPProxy():Promise<void>;

export function StartTor(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function StopHTTPProxy():Promise<void>;

export function StopTor():Promise<void>;

export function TestConnection():Promise<main.TestResult>;

export function TestSpeed():Promise<main.SpeedResult>;

export function UnsetSystemProxy():Promise<void>;
