// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMultiSlot(arg1) {
  return window['go']['main']['App']['AddMultiSlot'](arg1);
}

export function CheckSlotHealthNow(arg1) {
  return window['go']['main']['App']['CheckSlotHealthNow'](arg1);
}

export function DeleteMultiSlot(arg1) {
  return window['go']['main']['App']['DeleteMultiSlot'](arg1);
}

export function DownloadAllBridges() {
  return window['go']['main']['App']['DownloadAllBridges']();
}

export function GenerateSlotTorrc(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['GenerateSlotTorrc'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function GenerateTorrc(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GenerateTorrc'](arg1, arg2, arg3, arg4);
}

export function GetBestAutoProxySlot() {
  return window['go']['main']['App']['GetBestAutoProxySlot']();
}

export function GetBridgeFiles() {
  return window['go']['main']['App']['GetBridgeFiles']();
}

export function GetBridgeInfo() {
  return window['go']['main']['App']['GetBridgeInfo']();
}

export function GetBridgeLines(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetBridgeLines'](arg1, arg2, arg3);
}

export function GetCustomBridges() {
  return window['go']['main']['App']['GetCustomBridges']();
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetMultiSlots() {
  return window['go']['main']['App']['GetMultiSlots']();
}

export function GetSafeFilename(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetSafeFilename'](arg1, arg2, arg3);
}

export function GetSlotLogs(arg1) {
  return window['go']['main']['App']['GetSlotLogs'](arg1);
}

export function GetSlotTrafficStats(arg1) {
  return window['go']['main']['App']['GetSlotTrafficStats'](arg1);
}

export function GetTorExePath() {
  return window['go']['main']['App']['GetTorExePath']();
}

export function GetTrafficStats() {
  return window['go']['main']['App']['GetTrafficStats']();
}

export function GetUptime() {
  return window['go']['main']['App']['GetUptime']();
}

export function GetWorkingBridges() {
  return window['go']['main']['App']['GetWorkingBridges']();
}

export function GetWorkingBridgesText() {
  return window['go']['main']['App']['GetWorkingBridgesText']();
}

export function IsPortFree(arg1) {
  return window['go']['main']['App']['IsPortFree'](arg1);
}

export function IsTorConnected() {
  return window['go']['main']['App']['IsTorConnected']();
}

export function IsTorInstalled() {
  return window['go']['main']['App']['IsTorInstalled']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function NotifyDesktop(arg1, arg2) {
  return window['go']['main']['App']['NotifyDesktop'](arg1, arg2);
}

export function PingBridge(arg1, arg2, arg3) {
  return window['go']['main']['App']['PingBridge'](arg1, arg2, arg3);
}

export function PingCustomBridges(arg1) {
  return window['go']['main']['App']['PingCustomBridges'](arg1);
}

export function RequestNewCircuit() {
  return window['go']['main']['App']['RequestNewCircuit']();
}

export function ResetTrafficStats() {
  return window['go']['main']['App']['ResetTrafficStats']();
}

export function RetrySlot(arg1) {
  return window['go']['main']['App']['RetrySlot'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveCustomBridges(arg1, arg2) {
  return window['go']['main']['App']['SaveCustomBridges'](arg1, arg2);
}

export function SaveMultiSlots(arg1) {
  return window['go']['main']['App']['SaveMultiSlots'](arg1);
}

export function ScanBridges(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ScanBridges'](arg1, arg2, arg3, arg4, arg5);
}

export function SetProxyToSlot(arg1) {
  return window['go']['main']['App']['SetProxyToSlot'](arg1);
}

export function SetSystemProxy() {
  return window['go']['main']['App']['SetSystemProxy']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartAllSlots() {
  return window['go']['main']['App']['StartAllSlots']();
}

export function StartAutoConnect() {
  return window['go']['main']['App']['StartAutoConnect']();
}

export function StartHTTPProxy() {
  return window['go']['main']['App']['StartHTTPProxy']();
}

export function StartKeepAlive() {
  return window['go']['main']['App']['StartKeepAlive']();
}

export function StartTor(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartTor'](arg1, arg2, arg3, arg4);
}

export function StartWatchdog() {
  return window['go']['main']['App']['StartWatchdog']();
}

export function StopAllSlots() {
  return window['go']['main']['App']['StopAllSlots']();
}

export function StopAutoConnect() {
  return window['go']['main']['App']['StopAutoConnect']();
}

export function StopHTTPProxy() {
  return window['go']['main']['App']['StopHTTPProxy']();
}

export function StopKeepAlive() {
  return window['go']['main']['App']['StopKeepAlive']();
}

export function StopScan() {
  return window['go']['main']['App']['StopScan']();
}

export function StopSlot(arg1) {
  return window['go']['main']['App']['StopSlot'](arg1);
}

export function StopTor() {
  return window['go']['main']['App']['StopTor']();
}

export function StopWatchdog() {
  return window['go']['main']['App']['StopWatchdog']();
}

export function TestConnection() {
  return window['go']['main']['App']['TestConnection']();
}

export function TestSlotConnection(arg1) {
  return window['go']['main']['App']['TestSlotConnection'](arg1);
}

export function TestSpeed() {
  return window['go']['main']['App']['TestSpeed']();
}

export function UnsetSystemProxy() {
  return window['go']['main']['App']['UnsetSystemProxy']();
}
