// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddMultiSlot(arg1:main.SlotDef):Promise<void>;

export function CheckSlotHealthNow(arg1:string):Promise<void>;

export function DeleteMultiSlot(arg1:string):Promise<void>;

export function DownloadAllBridges():Promise<void>;

export function GenerateSlotTorrc(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string,arg7:boolean):Promise<string>;

export function GenerateTorrc(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetBestAutoProxySlot():Promise<string>;

export function GetBridgeFiles():Promise<Array<Record<string, string>>>;

export function GetBridgeInfo():Promise<main.BridgeOverview>;

export function GetBridgeLines(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;

export function GetCustomBridges():Promise<Record<string, any>>;

export function GetDataDir():Promise<string>;

export function GetMultiSlots():Promise<Array<main.SlotDef>>;

export function GetSafeFilename(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetSlotLogs(arg1:string):Promise<Array<string>>;

export function GetSlotTrafficStats(arg1:string):Promise<main.SlotTrafficResult>;

export function GetTorExePath():Promise<string>;

export function GetTrafficStats():Promise<Record<string, string>>;

export function GetUptime():Promise<string>;

export function GetWorkingBridges():Promise<Array<string>>;

export function GetWorkingBridgesText():Promise<string>;

export function IsPortFree(arg1:number):Promise<boolean>;

export function IsTorConnected():Promise<boolean>;

export function IsTorInstalled():Promise<boolean>;

export function LoadConfig():Promise<main.Config>;

export function NotifyDesktop(arg1:string,arg2:string):Promise<void>;

export function PingBridge(arg1:string,arg2:number,arg3:number):Promise<main.PingResult>;

export function PingCustomBridges(arg1:string):Promise<Array<main.PingResult>>;

export function RequestNewCircuit():Promise<void>;

export function ResetTrafficStats():Promise<void>;

export function RetrySlot(arg1:string):Promise<void>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SaveCustomBridges(arg1:string,arg2:boolean):Promise<void>;

export function SaveMultiSlots(arg1:Array<main.SlotDef>):Promise<void>;

export function ScanBridges(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<void>;

export function SetProxyToSlot(arg1:string):Promise<void>;

export function SetSystemProxy():Promise<void>;

export function ShowWindow():Promise<void>;

export function StartAllSlots():Promise<void>;

export function StartAutoConnect():Promise<void>;

export function StartHTTPProxy():Promise<void>;

export function StartKeepAlive():Promise<void>;

export function StartTor(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function StartWatchdog():Promise<void>;

export function StopAllSlots():Promise<void>;

export function StopAutoConnect():Promise<void>;

export function StopHTTPProxy():Promise<void>;

export function StopKeepAlive():Promise<void>;

export function StopScan():Promise<void>;

export function StopSlot(arg1:string):Promise<void>;

export function StopTor():Promise<void>;

export function StopWatchdog():Promise<void>;

export function TestConnection():Promise<main.TestResult>;

export function TestSlotConnection(arg1:string):Promise<main.TestResult>;

export function TestSpeed():Promise<main.SpeedResult>;

export function UnsetSystemProxy():Promise<void>;
